"""group join rules: approval, toggle, unique 8-char

Revision ID: 5771c26e3eed
Revises: 21317dbd2282
Create Date: 2026-09-21 11:40:36.955213

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5771c26e3eed'
down_revision: Union[str, Sequence[str], None] = '21317dbd2282'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('groups', schema=None) as batch_op:
        batch_op.add_column(sa.Column('join_enabled', sa.Boolean(), server_default=sa.true(), nullable=False))
        batch_op.create_unique_constraint(batch_op.f('uq_groups_join_password'), ['join_password'])
        batch_op.drop_column('requires_approval')

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('groups', schema=None) as batch_op:
        batch_op.add_column(sa.Column('requires_approval', sa.Boolean(), server_default=sa.false(), nullable=False))
        batch_op.drop_constraint(batch_op.f('uq_groups_join_password'), type_='unique')
        batch_op.drop_column('join_enabled')

    # ### end Alembic commands ###
