"""support jetons site settings

Revision ID: e72f7f80ab09
Revises: c3f1a2b4d5e6
Create Date: 2026-09-28 17:11:20.358800

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e72f7f80ab09'
down_revision: Union[str, Sequence[str], None] = 'c3f1a2b4d5e6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('gift_jetons',
    sa.Column('code', sa.String(length=40), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=False),
    sa.Column('icon', sa.String(length=32), nullable=False),
    sa.Column('tier', sa.String(length=16), nullable=False),
    sa.Column('price_uzs', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_gift_jetons')),
    sa.UniqueConstraint('code', name=op.f('uq_gift_jetons_code'))
    )
    op.create_table('site_settings',
    sa.Column('key', sa.String(length=64), nullable=False),
    sa.Column('value', sa.JSON(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('key', name=op.f('pk_site_settings'))
    )
    op.create_table('jeton_ledger',
    sa.Column('teacher_id', sa.Uuid(), nullable=False),
    sa.Column('jeton_code', sa.String(length=40), nullable=False),
    sa.Column('delta', sa.Integer(), nullable=False),
    sa.Column('kind', sa.String(length=16), nullable=False),
    sa.Column('ref_id', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['teacher_id'], ['users.id'], name=op.f('fk_jeton_ledger_teacher_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_jeton_ledger'))
    )
    with op.batch_alter_table('jeton_ledger', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_jeton_ledger_teacher_id'), ['teacher_id'], unique=False)

    op.create_table('jeton_orders',
    sa.Column('teacher_id', sa.Uuid(), nullable=False),
    sa.Column('jeton_code', sa.String(length=40), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('amount_uzs', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('teacher_note', sa.String(length=500), nullable=True),
    sa.Column('admin_note', sa.String(length=500), nullable=True),
    sa.Column('decided_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['teacher_id'], ['users.id'], name=op.f('fk_jeton_orders_teacher_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_jeton_orders'))
    )
    with op.batch_alter_table('jeton_orders', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_jeton_orders_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_jeton_orders_teacher_id'), ['teacher_id'], unique=False)

    op.create_table('support_messages',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('kind', sa.String(length=16), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('admin_reply', sa.Text(), nullable=True),
    sa.Column('replied_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_support_messages_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_support_messages'))
    )
    with op.batch_alter_table('support_messages', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_support_messages_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_support_messages_user_id'), ['user_id'], unique=False)

    with op.batch_alter_table('assignments') as batch_op:
        batch_op.add_column(sa.Column('ai_params', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('assignments') as batch_op:
        batch_op.drop_column('ai_params')
    with op.batch_alter_table('support_messages', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_support_messages_user_id'))
        batch_op.drop_index(batch_op.f('ix_support_messages_status'))

    op.drop_table('support_messages')
    with op.batch_alter_table('jeton_orders', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_jeton_orders_teacher_id'))
        batch_op.drop_index(batch_op.f('ix_jeton_orders_status'))

    op.drop_table('jeton_orders')
    with op.batch_alter_table('jeton_ledger', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_jeton_ledger_teacher_id'))

    op.drop_table('jeton_ledger')
    op.drop_table('site_settings')
    op.drop_table('gift_jetons')
    # ### end Alembic commands ###
