"""avatars xp badges

Revision ID: ba4174308ff3
Revises: 4d3de08fae1c
Create Date: 2026-09-21 14:56:39.859047

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ba4174308ff3'
down_revision: Union[str, Sequence[str], None] = '4d3de08fae1c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('badge_awards',
    sa.Column('student_id', sa.Uuid(), nullable=False),
    sa.Column('badge_code', sa.String(length=40), nullable=False),
    sa.Column('source', sa.String(length=16), nullable=False),
    sa.Column('group_id', sa.Uuid(), nullable=True),
    sa.Column('given_by', sa.Uuid(), nullable=True),
    sa.Column('period', sa.String(length=7), nullable=True),
    sa.Column('meta', sa.JSON(), nullable=True),
    sa.Column('awarded_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['given_by'], ['users.id'], name=op.f('fk_badge_awards_given_by_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['group_id'], ['groups.id'], name=op.f('fk_badge_awards_group_id_groups'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['student_id'], ['users.id'], name=op.f('fk_badge_awards_student_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_badge_awards'))
    )
    with op.batch_alter_table('badge_awards', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_badge_awards_awarded_at'), ['awarded_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_badge_awards_badge_code'), ['badge_code'], unique=False)
        batch_op.create_index(batch_op.f('ix_badge_awards_period'), ['period'], unique=False)
        batch_op.create_index(batch_op.f('ix_badge_awards_student_id'), ['student_id'], unique=False)

    op.create_table('xp_events',
    sa.Column('student_id', sa.Uuid(), nullable=False),
    sa.Column('group_id', sa.Uuid(), nullable=False),
    sa.Column('submission_id', sa.Uuid(), nullable=False),
    sa.Column('points', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['group_id'], ['groups.id'], name=op.f('fk_xp_events_group_id_groups'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['student_id'], ['users.id'], name=op.f('fk_xp_events_student_id_users'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['submission_id'], ['submissions.id'], name=op.f('fk_xp_events_submission_id_submissions'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_xp_events')),
    sa.UniqueConstraint('submission_id', name=op.f('uq_xp_events_submission_id'))
    )
    with op.batch_alter_table('xp_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_xp_events_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_xp_events_group_id'), ['group_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_xp_events_student_id'), ['student_id'], unique=False)

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('avatar_key', sa.String(length=128), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('avatar_key')

    with op.batch_alter_table('xp_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_xp_events_student_id'))
        batch_op.drop_index(batch_op.f('ix_xp_events_group_id'))
        batch_op.drop_index(batch_op.f('ix_xp_events_created_at'))

    op.drop_table('xp_events')
    with op.batch_alter_table('badge_awards', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_badge_awards_student_id'))
        batch_op.drop_index(batch_op.f('ix_badge_awards_period'))
        batch_op.drop_index(batch_op.f('ix_badge_awards_badge_code'))
        batch_op.drop_index(batch_op.f('ix_badge_awards_awarded_at'))

    op.drop_table('badge_awards')
    # ### end Alembic commands ###
