"""promo codes

Revision ID: 3d9c19eb50ed
Revises: e72f7f80ab09
Create Date: 2026-09-29 09:55:20.098077

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3d9c19eb50ed'
down_revision: Union[str, Sequence[str], None] = 'e72f7f80ab09'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('promo_codes',
    sa.Column('code', sa.String(length=32), nullable=False),
    sa.Column('kind', sa.String(length=16), nullable=False),
    sa.Column('value', sa.Integer(), nullable=False),
    sa.Column('plan_code', sa.String(length=32), nullable=True),
    sa.Column('max_uses', sa.Integer(), nullable=True),
    sa.Column('valid_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('note', sa.String(length=255), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_promo_codes')),
    sa.UniqueConstraint('code', name=op.f('uq_promo_codes_code'))
    )
    with op.batch_alter_table('plan_requests', schema=None) as batch_op:
        batch_op.add_column(sa.Column('discount_uzs', sa.Integer(), server_default='0', nullable=False))
        batch_op.add_column(sa.Column('promo_code_id', sa.Uuid(), nullable=True))
        batch_op.create_index(batch_op.f('ix_plan_requests_promo_code_id'), ['promo_code_id'], unique=False)
        batch_op.create_foreign_key(batch_op.f('fk_plan_requests_promo_code_id_promo_codes'), 'promo_codes', ['promo_code_id'], ['id'], ondelete='SET NULL')

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('plan_requests', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_plan_requests_promo_code_id_promo_codes'), type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_plan_requests_promo_code_id'))
        batch_op.drop_column('promo_code_id')
        batch_op.drop_column('discount_uzs')

    op.drop_table('promo_codes')
    # ### end Alembic commands ###
