"""email auth admin plan requests

Revision ID: 9a067f025d91
Revises: ba4174308ff3
Create Date: 2026-09-21 17:44:54.464006

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9a067f025d91'
down_revision: Union[str, Sequence[str], None] = 'ba4174308ff3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('plan_requests',
    sa.Column('teacher_id', sa.Uuid(), nullable=False),
    sa.Column('plan_id', sa.Uuid(), nullable=False),
    sa.Column('months', sa.Integer(), nullable=False),
    sa.Column('amount_uzs', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('teacher_note', sa.String(length=500), nullable=True),
    sa.Column('admin_note', sa.String(length=500), nullable=True),
    sa.Column('decided_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('decided_by', sa.Uuid(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['decided_by'], ['users.id'], name=op.f('fk_plan_requests_decided_by_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['plan_id'], ['plans.id'], name=op.f('fk_plan_requests_plan_id_plans')),
    sa.ForeignKeyConstraint(['teacher_id'], ['users.id'], name=op.f('fk_plan_requests_teacher_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_plan_requests'))
    )
    with op.batch_alter_table('plan_requests', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_plan_requests_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_plan_requests_teacher_id'), ['teacher_id'], unique=False)

    # Ustun nomi o'zgaradi (ma'lumot saqlanadi): phone -> target, uzunligi email uchun 254
    with op.batch_alter_table('otp_codes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_otp_codes_phone'))
        batch_op.alter_column('phone', new_column_name='target', existing_type=sa.String(length=16),
                              type_=sa.String(length=254), existing_nullable=False)
    with op.batch_alter_table('otp_codes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_otp_codes_target'), ['target'], unique=False)

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('email', sa.String(length=254), nullable=True))
        batch_op.add_column(sa.Column('password_hash', sa.String(length=255), nullable=True))
        batch_op.alter_column('phone',
               existing_type=sa.VARCHAR(length=16),
               nullable=True)
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_email'))
        batch_op.alter_column('phone',
               existing_type=sa.VARCHAR(length=16),
               nullable=False)
        batch_op.drop_column('password_hash')
        batch_op.drop_column('email')

    with op.batch_alter_table('otp_codes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_otp_codes_target'))
        batch_op.alter_column('target', new_column_name='phone', existing_type=sa.String(length=254),
                              type_=sa.String(length=16), existing_nullable=False)
    with op.batch_alter_table('otp_codes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_otp_codes_phone'), ['phone'], unique=False)

    with op.batch_alter_table('plan_requests', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_plan_requests_teacher_id'))
        batch_op.drop_index(batch_op.f('ix_plan_requests_status'))

    op.drop_table('plan_requests')
    # ### end Alembic commands ###
